extensions:
  health_check:
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  awsxray:
    endpoint: 0.0.0.0:2000
    transport: udp
  statsd:
    endpoint: 0.0.0.0:8125
    aggregation_interval: 60s

processors:
  batch/traces:
    timeout: 1s
    send_batch_size: 50
  batch/metrics:
    timeout: 60s
  transform/redact:
    trace_statements:
      - context: resource
        statements:
          - replace_pattern(attributes["process.command_line"], "-Dplay.http.secret.key=[^\\s]*", "-Dplay.http.secret.key=REDACTED")
          - replace_pattern(attributes["process.command_line"], "-Dauth.secret=[^\\s]*", "-Dauth.secret=REDACTED")
    metric_statements:
      - context: resource
        statements:
          - replace_pattern(attributes["process.command_line"], "-Dplay.http.secret.key=[^\\s]*", "-Dplay.http.secret.key=REDACTED")
          - replace_pattern(attributes["process.command_line"], "-Dauth.secret=[^\\s]*", "-Dauth.secret=REDACTED")

exporters:
  logging:
  awsxray:
    indexed_attributes: ["ConsignmentId", "UserId"]
  awsemf:
    namespace: ECS/AWSOTel/Application
    log_group_name: '/aws/ecs/application/metrics'

service:
  pipelines:
    traces:
      receivers: [otlp, awsxray]
      processors: [batch/traces, transform/redact]
      exporters: [awsxray]
    metrics:
      receivers: [otlp, statsd]
      processors: [batch/metrics, transform/redact]
      exporters: [awsemf]

  extensions: [health_check]
